[build]
  [[build.buildpacks]]
    id = "heroku/python"
    version = "0.1.0"
  
  [[build.buildpacks]]
    id = "heroku/nodejs"
    version = "0.1.0"

[metadata]
  [metadata.buildpacks]
    [metadata.buildpacks.python]
      version = "3.12"
    
    [metadata.buildpacks.nodejs]
      version = "20"

[launch]
  cmd = "cd backend && python run.py"
