[build]
  [[build.buildpacks]]
    id = "heroku/python"
    version = "0.1.0"
    env = [
      "PYTHON_VERSION=3.11.7"
    ]
  
  [[build.buildpacks]]
    id = "heroku/nodejs"
    version = "0.1.0"
    env = [
      "NODE_ENV=production",
      "NPM_CONFIG_PRODUCTION=false"
    ]

[metadata]
  [metadata.buildpacks]
    [metadata.buildpacks.python]
      version = "3.11.7"
    
    [metadata.buildpacks.nodejs]
      version = "20"

[launch]
  cmd = "cd backend && python run.py"
